# Generated by Django 3.1.3 on 2020-11-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bay', '0002_cart_ordereditem_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='deliveryInfo',
            field=models.TextField(blank=True),
        ),
    ]
