# Generated by Django 3.1.3 on 2020-11-20 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Bay', '0003_cart_deliveryinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='petSitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogBreed', models.CharField(max_length=1000)),
                ('days', models.IntegerField(default=0)),
                ('unit', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('date', models.DateTimeField(null=True)),
                ('deliveryInfo', models.TextField(blank=True)),
                ('serviced', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dogWalking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogSize', models.CharField(max_length=1000)),
                ('hours', models.IntegerField(default=0)),
                ('unit', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('date', models.DateTimeField(null=True)),
                ('deliveryInfo', models.TextField(blank=True)),
                ('serviced', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dogGrooming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogBreed', models.CharField(max_length=1000)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('date', models.DateTimeField(null=True)),
                ('deliveryInfo', models.TextField(blank=True)),
                ('serviced', models.BooleanField(default=False)),
                ('sessions', models.ManyToManyField(blank=True, to='Bay.sessions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
